export const books = [
  {
    title: 'The Algorithm Design Manual',
    author: 'Steven S. Skiena',
    category: 'Computer Science',
    totalCopies: '5',
    availableCopies: '3',
    publishYear: '2008',
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    category: 'Science Fiction',
    totalCopies: '5',
    availableCopies: '5',
    publishYear: '1965',
  },
  {
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    category: 'Fantasy',
    totalCopies: '2',
    availableCopies: '2',
    publishYear: '1954',
  },
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    category: 'Software Engineering',
    totalCopies: '4',
    availableCopies: '1',
    publishYear: '2008',
  },
  {
    title: '1984',
    author: 'George Orwell',
    category: 'Dystopian',
    totalCopies: '6',
    availableCopies: '4',
    publishYear: '1949',
  },
  {
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    category: 'Science',
    totalCopies: '3',
    availableCopies: '2',
    publishYear: '1988',
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    category: 'Classic Literature',
    totalCopies: '5',
    availableCopies: '3',
    publishYear: '1960',
  },
  {
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    category: 'Computer Science',
    totalCopies: '4',
    availableCopies: '2',
    publishYear: '2009',
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt & David Thomas',
    category: 'Software Development',
    totalCopies: '3',
    availableCopies: '2',
    publishYear: '1999',
  },
  {
    title: 'The Martian',
    author: 'Andy Weir',
    category: 'Science Fiction',
    totalCopies: '4',
    availableCopies: '4',
    publishYear: '2011',
  },
  {
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    category: 'Classic Literature',
    totalCopies: '6',
    availableCopies: '3',
    publishYear: '1951',
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    category: 'History',
    totalCopies: '5',
    availableCopies: '5',
    publishYear: '2011',
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    category: 'Psychology',
    totalCopies: '4',
    availableCopies: '4',
    publishYear: '2011',
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    category: 'Dystopian',
    totalCopies: '3',
    availableCopies: '1',
    publishYear: '1932',
  },
  {
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    category: 'Fantasy',
    totalCopies: '4',
    availableCopies: '3',
    publishYear: '2007',
  },
  {
    title: 'The Lean Startup',
    author: 'Eric Ries',
    category: 'Business',
    totalCopies: '3',
    availableCopies: '2',
    publishYear: '2011',
  },
  {
    title: 'Zero to One',
    author: 'Peter Thiel',
    category: 'Entrepreneurship',
    totalCopies: '2',
    availableCopies: '2',
    publishYear: '2014',
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: 'J.K. Rowling',
    category: 'Fantasy',
    totalCopies: '7',
    availableCopies: '5',
    publishYear: '1997',
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    category: 'Classic Literature',
    totalCopies: '5',
    availableCopies: '3',
    publishYear: '1925',
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: 'Douglas Adams',
    category: 'Science Fiction',
    totalCopies: '4',
    availableCopies: '4',
    publishYear: '1979',
  },
]
